"""Editorial source, 35 revised scripts. Data only; no publishing side effects."""
# id, theme, audience, pillar, stage, structure, visual, headline, spoken hook,
# body beats (remaining stages except CTA), reward, specific revision
REELS = [
(1, 'Antes de contratar ou construir', 'dono', 'RASTREAR', 'Descoberta', 'CRESA',
 'Duas propostas na mesa; colocar entre elas um cartão escrito PROBLEMA.', 'A pergunta que falta nas duas propostas',
 'Antes de contratar uma agência ou abrir o editor de código, responde uma coisa: o que precisa mudar na sua empresa?',
 ['Se a resposta é só “preciso de um sistema”, ainda falta a parte que orienta a decisão.',
  'O erro é comparar ferramentas antes de combinar o resultado. Você pode receber exatamente o que pediu e continuar com o mesmo gargalo.',
  'Escreve quem sofre com o problema, quando ele aconteceu pela última vez e como você vai perceber que melhorou. Esse é o primeiro movimento do Gambito de Valor.'], 'MAPA',
 'Sai a falsa escolha agência ruim versus construir sozinho; entra critério de contratação.'),
(2, 'Demo que ajuda a decidir', 'prestador', 'VIBE CODAR', 'Consideração', 'NPPC',
 'Tela dividida: lista de funcionalidades versus uma tarefa concluída em ambiente de teste.', 'O detalhe que falta na sua demo',
 'Sua demonstração mostra um monte de função, mas o cliente ainda não sabe por que deveria comprar?',
 ['Troca o tour pela tarefa que ele já faz. Pede um exemplo, combina o que seria uma boa resposta e mostra essa mesma tarefa no protótipo.',
  'A primeira vitória não é ouvir “que legal”. É o cliente conseguir comparar o jeito atual com o teste e apontar o que mudou. A proposta vem com esse contexto, não no lugar dele.'], 'PROVA',
 'Removido primeiro cliente em dez minutos sem fonte. Demo não elimina objeções.'),
(3, 'As três perguntas antes da IA', 'dono', 'RASTREAR', 'Consideração', 'COBA',
 'Riscar “qual IA?” e escrever três perguntas em um papel.', 'Você está começando pela pergunta errada?',
 'Qual IA eu compro? Essa costuma ser a segunda conversa. A primeira é sobre o que está travando.',
 ['Quando isso aconteceu pela última vez? Quem precisou parar o trabalho para resolver? O que vocês fizeram naquela hora?',
  'Essas três perguntas tiram a conversa do “seria legal ter” e trazem uma situação real. Pode terminar em automação. Pode terminar num ajuste de processo bem menor.'], 'MAPA',
 'As três perguntas agora são entregues no vídeo e no material; não substituídas por oferta.'),
(4, 'Subir não é operar', 'dono', 'VIBE CODAR', 'Descoberta', 'CRESA',
 'Mostrar uma página abrindo; virar três cartões: BACKUP, ACESSO, RESPONSÁVEL.', 'A parte que o vídeo de instalação não mostra',
 'O sistema abriu no navegador. Ótimo. Agora, quem cuida dele quando alguma coisa falha?',
 ['É fácil se empolgar com uma instalação rápida. Eu também gosto de ver a tela funcionar.',
  'Só que o comando não responde quem restaura o backup, quem atualiza e quem pode acessar os dados.',
  'Antes de usar na operação, combine essas três responsabilidades. O valor não é só colocar no ar: é a empresa conseguir usar sem depender de sorte.'], 'INFRA',
 'Sem promessa de stack inteira ou backup garantido por um comando.'),
(5, 'Atendimento rápido não basta', 'dono', 'MONETIZAR', 'Consideração', 'CRESA',
 'Cronômetro de resposta rápida ao lado de conversa sem próximo passo, com dados fictícios.', 'Respondeu rápido. E depois?',
 'Seu atendimento responde em segundos e mesmo assim a conversa morre?',
 ['Olha uma conversa recente. A pessoa recebeu informação, mas entendeu o que precisava fazer depois?',
  'O erro é usar velocidade como se fosse venda. Resposta rápida ajuda, mas não substitui oferta clara nem acompanhamento.',
  'Revise algumas conversas: dúvida resolvida, próximo passo e responsável. Sem esse contexto, calcular “receita perdida” só pelo tempo de resposta é chute.'], 'FUNIL',
 'Sai cálculo que tratava hipótese como dinheiro comprovadamente perdido.'),
(6, 'Pergunta real vira conteúdo', 'dono', 'RASTREAR', 'Descoberta', 'AIDA',
 'Post-it “quanto custa?” virando três ângulos no quadro.', 'Essa pergunta do cliente rende mais do que parece',
 'A pergunta que você respondeu de novo hoje pode ser o seu próximo vídeo.',
 ['Pega “quanto custa?”. Em vez de gravar uma tabela de preços, mostra o que muda o orçamento, quando a solução não vale a pena e o que a pessoa precisa trazer para decidir.',
  'Você não precisa inventar assunto. Precisa traduzir uma dúvida real em uma decisão que o cliente consiga tomar. Um vídeo, uma pergunta, uma pequena resposta útil.'], 'CONTEUDO',
 'Material entrega perguntas e ficha de pauta, não apenas uma página de serviço.'),
(7, 'Produto não é negócio', 'prestador', 'MONETIZAR', 'Consideração', 'ISAC',
 'Dois papéis: USUÁRIOS e CUSTO DE OPERAR; não mostrar contas de clientes.', 'O sistema funcionava. A conta não fechava.',
 'Meu Laboratório de Insights chegou a setenta usuários. E isso não bastou para o negócio sobreviver.',
 ['Eu já contei essa história: a infraestrutura custava mais do que a receita, e uma entrega importante não saiu antes da renovação. O produto existia, mas a operação não se sustentou.',
  'A lição não é que usuário não importa. É que eu precisava olhar também para custo, entrega e renovação. Hoje, quando penso numa solução, a conta de manter aquilo faz parte da construção.'], 'PROVA',
 'Relato pessoal publicado na auditoria, não balanço financeiro auditado. Não atribuir tudo a falta de demanda.'),
(8, 'Ferramenta nova ou processo?', 'dono', 'RASTREAR', 'Consideração', 'COBA',
 'Fechar abas de ferramentas e deixar uma única conversa de exemplo anonimizada.', 'Talvez você não precise de outra assinatura',
 'Antes de assinar mais uma ferramenta, escolhe uma tarefa que precisa melhorar.',
 ['Pode ser orçamento sem retorno, cadastro duplicado ou pergunta repetida. Agora confere se o que você já paga resolve uma parte disso e por que essa parte não está sendo usada.',
  'Às vezes falta integração. Às vezes falta responsável. E às vezes precisa, sim, de outra ferramenta. O diagnóstico serve para separar essas situações antes do próximo boleto.'], 'MAPA',
 'Sem afirmar que ferramenta cara é necessariamente ruim ou que grátis sempre resolve.'),
(9, 'Velocidade não é receita', 'prestador', 'VIBE CODAR', 'Consideração', 'COBA',
 'Desenhar duas colunas: CONSTRUIR e NEGÓCIO; preencher critérios diferentes.', 'Construir mais rápido resolve qual parte?',
 'Na Voice Dream, eu estimava dois anos sem IA. Com IA e open source, construímos em dois meses.',
 ['Essa é a minha experiência, não um prazo que eu prometeria para qualquer projeto. Acelerar a construção mudou a viabilidade de testar aquela ideia.',
  'Mas tempo de desenvolvimento não mede sozinho o negócio. Ainda entram demanda, adoção, custos e receita. O Gambito de Valor não termina no deploy: ele obriga a olhar para a próxima jogada.'], 'PROVA',
 'Mantida estimativa pessoal publicada; retirado uso de aporte/equity como prova de receita.'),
(10, 'Recorte específico de oportunidade', 'prestador', 'RASTREAR', 'Consideração', 'DDC',
 'Apagar “IA para empresas” e escrever uma situação operacional específica.', 'Seu concorrente vende IA. E você?',
 '“Faço automação com IA” explica a ferramenta. Ainda não explica por que escolher você.',
 ['Compara com “ajudo equipes a não esquecer orçamentos sem retorno”. A segunda frase dá uma situação para o comprador reconhecer. Ainda precisa de prova, mas já permite uma conversa concreta.',
  'O recorte não precisa ser um mercado sem concorrência. Precisa ser um problema que você entende, consegue demonstrar e sabe atender. Qual situação aparece de novo nos seus clientes?'], 'MAPA',
 'Sem declarar que mercados não saturam ou que sempre existe oportunidade lucrativa.'),
(11, 'Primeiro teste de infraestrutura', 'dono', 'VIBE CODAR', 'Descoberta', 'AAA',
 'Apontar para botão RESTAURAR em um checklist, não executar em produção.', 'O botão que vale testar antes da emergência',
 'Antes de colocar o CRM no centro da empresa, pergunta se alguém já testou a restauração do backup.',
 ['“O backup roda” e “conseguimos recuperar” são coisas diferentes. Combine um teste isolado, o que será restaurado e quem valida os dados. Não teste apagando o sistema que atende clientes. A pequena vitória aqui é descobrir a dependência enquanto ainda dá para planejar.'], 'INFRA',
 'Substitui promessa de resolver servidor em cinco minutos por teste seguro e relevante.'),
(12, 'Alternativa que o cliente já usa', 'prestador', 'RASTREAR', 'Consideração', 'ISAC',
 'Abrir ficha: PROBLEMA / COMO RESOLVE HOJE / POR QUE MUDARIA.', 'Seu concorrente talvez nem seja uma empresa',
 'No JURISMART, eu terminei o gerador de petições e encontrei advogados que já faziam aquilo no ChatGPT.',
 ['É uma história que eu já compartilhei, e ela mudou a pergunta que eu faço antes de construir. Não basta achar a tarefa interessante. Preciso entender a alternativa que a pessoa já usa.',
  'Uma planilha, um assistente ou o próprio ChatGPT podem ser suficientes para ela. A próxima solução precisa ter um motivo concreto para a troca. Hoje eu investigo isso antes de me apaixonar pela interface.'], 'MAPA',
 'Preserva relato publicado e não transforma experiência individual em regra universal.'),
(13, 'Prova para discutir preço', 'prestador', 'MONETIZAR', 'Consideração', 'COBA',
 'Trocar cartão “sou especialista” por uma tarefa antes/depois, marcada demonstração.', 'O preço fica sozinho quando falta isso',
 'Quando a proposta só lista o que você vai fazer, o cliente precisa adivinhar para que aquilo serve.',
 ['Mostre o problema, a situação atual e o resultado que o teste permite verificar. Diferencie o que você demonstrou do que ainda depende de implantação.',
  'Isso não faz o preço virar detalhe. Faz a negociação ter mais informação: escopo, risco, alternativa e valor percebido. Uma prova honesta ajuda mais do que um número de economia inventado.'], 'PROVA',
 'Retiradas propostas com diferença de 5x e economia sem fonte.'),
(14, 'Custo de manter a stack', 'dono', 'VIBE CODAR', 'Consideração', 'CRESA',
 'Pilha de cartões de ferramentas; retirar até sobrar o fluxo necessário.', 'A escolha barata pode cobrar depois',
 'Na hora de escolher a stack, você está olhando só para a instalação ou também para quem vai manter?',
 ['A ferramenta nova chama atenção. A parte de atualizar, integrar e recuperar costuma ficar para depois.',
  'O erro é comparar só o preço da licença. Infraestrutura, manutenção e dependência de uma pessoa também entram na conta.',
  'Liste o fluxo que precisa funcionar e escolha o conjunto que sua equipe consegue operar. Simples não é ter menos recursos a qualquer custo: é entender a responsabilidade de cada peça.'], 'INFRA',
 'Retira prazo fabricado de três meses e mantém contraste concreto.'),
(15, 'Quando pedir ajuda de escopo', 'dono', 'MONETIZAR', 'Pré-conversão', 'AIDA',
 'Mostrar mapa com três portas: PÁGINA / ATENDIMENTO / OFERTA.', 'Onde você mexeria primeiro?',
 'Chega gente no seu site, mas a venda não anda. Você muda a página, o atendimento ou a oferta?',
 ['Sem olhar a jornada, dá para investir na etapa errada. Eu começo por onde a pessoa entra, o que foi prometido e qual passo ela consegue dar.',
  'Na Sessão de Start, a gente organiza esse problema em prioridade e PRD: escopo, dependências e critério de sucesso. É uma conversa paga para decidir a execução, não a implementação inteira.'], 'LASER',
 'Não sentencia que o anúncio está certo; explica a entrega concreta da consultoria.'),
(16, 'Gargalo com evidência', 'dono', 'RASTREAR', 'Consideração', 'AAA',
 'Marcar uma linha vazia em um fluxograma e aproximar a câmera.', 'Em qual etapa a sua operação fica muda?',
 'Você sabe onde a tarefa para quando ninguém está cobrando?',
 ['Escolhe um processo real: do pedido até a entrega, ou do contato até o orçamento. Em cada passagem, pergunta quem assume, qual é a próxima ação e onde fica o registro. A etapa sem resposta é uma hipótese de gargalo para investigar, não uma prova automática de prejuízo.'], 'MAPA',
 'Roteiro entrega um teste, em vez de só prometer mapeamento.'),
(17, 'Retomar projeto parado', 'dono', 'VIBE CODAR', 'Consideração', 'NPPC',
 'Cobrir um quadro cheio de tarefas e deixar visível uma única entrega.', 'O projeto parado pode estar pedindo menos',
 'Se o projeto travou, eu não começaria adicionando mais coisa. Escolheria uma entrega que dá para testar.',
 ['Escreve a tarefa que uma pessoa precisa concluir, o que entra e como você confere a saída. Se não cabe numa demonstração simples, talvez o recorte ainda esteja grande.',
  'Essa prova ajuda a descobrir a próxima decisão: seguir, corrigir ou parar. Não prometo lançar em três dias; proponho diminuir o tamanho da incerteza antes de aumentar o projeto.'], 'PROVA',
 'Sai case não comprovado de projeto no ar em três dias.'),
(18, 'Manifesto Gambito de Valor', 'ponte', 'RASTREAR', 'Consideração', 'COBA',
 'Tirar do tabuleiro um cartão “minha ideia favorita” e abrir espaço para “problema real”.', 'A ideia que você precisa tirar do caminho',
 'O primeiro movimento do meu Gambito de Valor é abrir mão da ideia que eu estava com vontade de construir.',
 ['No lugar dela, eu procuro um problema recente, alguém responsável e uma consequência que vale investigar. Depois monto o menor teste de utilidade. Só então discuto a solução e acompanho o resultado.',
  'Rastrear, construir, capturar. Não é vender sem trabalhar. É parar de gastar todo o trabalho numa coisa que ninguém precisava daquele jeito. Vibe coder constrói. Vibe Seller joga o Gambito de Valor.'], 'MAPA',
 'Mecanismo completo com sacrifício definido, sem promessa de renda fácil.'),
(19, 'Open source com custo real', 'dono', 'VIBE CODAR', 'Descoberta', 'CRESA',
 'Tela de licença ao lado de lista de infraestrutura, atualização e suporte.', 'Grátis em qual parte da conta?',
 'Um CRM open source pode reduzir gasto com licença. Mas não transforma a operação em custo zero.',
 ['Antes de trocar, compara as funções que sua equipe realmente usa: canais, histórico, permissões e integrações.',
  'O erro é chamar duas ferramentas de equivalentes só porque as telas parecem parecidas.',
  'Escolha uma tarefa para testar e inclua migração, hospedagem e manutenção na conta. A melhor opção é a que serve ao seu processo, não a que ganhou a discussão do feed.'], 'INFRA',
 'Sem afirmar equivalência total ao concorrente nem endosso de terceiros.'),
(20, 'Aprender a construir não escolhe a oferta', 'prestador', 'RASTREAR', 'Consideração', 'COBA',
 'Colocar uma folha “eu consigo fazer” sobre outra “alguém precisa”; destacar interseção.', 'Saber fazer ainda deixa uma pergunta aberta',
 'Eu já vinha do marketing quando comecei a construir com IA. Ganhei uma capacidade nova, não uma oferta pronta.',
 ['Agora dava para fazer mais coisas. Só que a pergunta continuava sendo: para quem isso resolve um problema importante? Saber vender não responde sozinho, e saber construir também não.',
  'O Gambito de Valor junta as duas conversas. Investigar a demanda orienta a construção; a demonstração ajuda a discutir a oferta. Não é uma competição entre quem programa e quem vende.'], 'MAPA',
 'Mantém origem pessoal sem hierarquia universal entre profissões.'),
(21, 'Indicação com processo', 'dono', 'MONETIZAR', 'Pré-conversão', 'COBA',
 'Cartão INDICAÇÃO entrando num funil com responsável, contexto e próximo passo.', 'Sua indicação entra onde?',
 'Receber cliente por indicação é ótimo. O problema é não ter um processo quando ele chega.',
 ['Quem indicou? O que a pessoa espera? Quem responde e registra o próximo passo? Um canal valioso também pode perder continuidade dentro da operação.',
  'Na Sessão de Start, a gente pode mapear esse caminho e documentar o que precisa mudar. Não é substituir indicação por anúncio: é dar estrutura ao que já traz gente até você.'], 'LASER',
 'Retira insulto “você teve sorte” e alegação de que indicação não escala.'),
(22, 'Pedir ajuda específica', 'dono', 'VIBE CODAR', 'Consideração', 'AIDA',
 'Mostrar pedido vago “não funciona” e trocar por entrada/saída/erro, sem credenciais.', 'Esse pedido de ajuda costuma travar junto',
 'Quando você pede “arruma meu sistema”, a outra pessoa ainda precisa descobrir o que está quebrado.',
 ['Mostra a tarefa esperada, o que aconteceu e um exemplo seguro. Se houver erro, envia a mensagem sem senhas ou dados de clientes.',
  'Esse pequeno recorte ajuda a separar configuração, infraestrutura e desenvolvimento. Dá para pedir suporte com mais clareza sem prometer que qualquer problema se resolve numa tarde.'], 'INFRA',
 'Sai suporte genérico implícito e prazo sem diagnóstico.'),
(23, 'Seguidores versus oportunidades', 'dono', 'RASTREAR', 'Descoberta', 'CRESA',
 'Tela com seguidores coberta por cartão: CLIQUE / CONVERSA / OPORTUNIDADE.', 'O crescimento que o contador não explica',
 'Seu perfil ganhou seguidores. Como você descobre se isso aproximou algum cliente?',
 ['O número anima, e pode ser um bom sinal de distribuição. Mas ele não conta o que aconteceu depois.',
  'O erro é usar seguidor como se fosse oportunidade comercial.',
  'Olhe o caminho: conteúdo, recompensa, clique e conversa qualificada. Onde os dados faltarem, marque a lacuna. Sem isso, você não sabe se precisa de outro tema ou de uma ponte melhor.'], 'FUNIL',
 'Sem alegar vendas orgânicas ou zero mídia paga não comprovados.'),
(24, 'Preço com contexto', 'prestador', 'MONETIZAR', 'Consideração', 'AAA',
 'Três cartões: CUSTO / VALOR / RISCO.', 'A pergunta do preço precisa de companhia',
 '“Quanto vale resolver isso?” ajuda a discutir preço. Mas não fecha a conta sozinha.',
 ['Você também precisa saber o que vai entregar, quanto custa manter e qual risco está assumindo. O valor percebido orienta a conversa; escopo e custos impedem você de vender uma promessa que não sustenta. Começa por um resultado verificável, não por multiplicar o preço no escuro.'], 'PROVA',
 'Retira experiência inventada de duas propostas e aumento de preço sem mudar nada.'),
(25, 'Comprar a própria proposta', 'dono', 'MONETIZAR', 'Consideração', 'AAA',
 'Circular três trechos ausentes numa proposta fictícia.', 'Você consegue decidir com essa proposta?',
 'Antes de aprovar um projeto de IA, procura três respostas na proposta.',
 ['Qual problema ela resolve? Como vocês vão testar a entrega? Quem fica responsável depois? Se só tem lista de tecnologias e prazo, peça essas respostas antes de comparar preço. Você não precisa dominar o código para exigir clareza sobre o que está comprando.'], 'PROVA',
 'Troca julgamento pessoal sobre cobrar por um critério útil ao decisor.'),
(26, 'Retrabalho que dá para observar', 'dono', 'RASTREAR', 'Consideração', 'COBA',
 'Mover o mesmo cartão entre duas pessoas duas vezes; legenda SIMULAÇÃO.', 'Por que essa tarefa voltou?',
 'Uma tarefa que volta para a mesma pessoa pode mostrar mais sobre o processo do que uma reunião inteira.',
 ['Pega um exemplo recente de retrabalho. Faltou informação na entrada? Mudou a regra? Ninguém sabia quem aprovava?',
  'Registra a causa e observa se se repete antes de automatizar. Talvez a primeira solução seja um campo obrigatório ou uma definição de responsabilidade. O ganho começa em enxergar a volta, não em inventar uma porcentagem.'], 'MAPA',
 'Sai alegação de 30% do tempo descoberto em cinco minutos.'),
(27, 'Descrever e testar', 'ponte', 'VIBE CODAR', 'Descoberta', 'DDC',
 'Comparar “faça um CRM” com um critério de aceite de uma tarefa.', 'O pedido parece claro. Para quem?',
 '“Cria um CRM para mim” e “registra esse contato sem duplicar” são pedidos de tamanhos bem diferentes.',
 ['No primeiro, a IA precisa adivinhar quase tudo. No segundo, você consegue explicar uma entrada, uma regra e um resultado esperado. Isso deixa o teste mais concreto.',
  'Construir com IA não dispensa conhecimento, revisão ou segurança. Mas aprender a descrever o problema já muda a qualidade da conversa. Qual tarefa você consegue explicar sem falar o nome da ferramenta?'], 'PROVA',
 'Sem dizer que um prompt vale mais que formação técnica.'),
(28, 'Preço baixo e escopo', 'prestador', 'MONETIZAR', 'Consideração', 'CRESA',
 'Preço fixo num papel; adicionar pedidos até o papel sair do quadro.', 'O desconto não foi a única concessão',
 'Você baixou o preço, mas combinou o que ficou de fora?',
 ['Quando a proposta está vaga, cada pedido novo parece pequeno. No fim, a entrega já não é a que você imaginou.',
  'O erro é negociar só o número e deixar o escopo aberto.',
  'Registre o que entra, o que não entra e como uma mudança será tratada. Isso não garante margem, mas evita uma parte da discussão que poderia ter sido resolvida antes da venda.'], 'PROVA',
 'Sem história pessoal não documentada nem promessa de acabar com objeção de preço.'),
(29, 'Bastidor com mensagem', 'ponte', 'VIBE CODAR', 'Descoberta', 'AAA',
 'Manter um erro verdadeiro de fala e a retomada; não encenar como espontâneo.', 'O take que eu não precisava esconder',
 'Eu errei essa fala. O que eu não posso é deixar a ideia incompreensível para quem assiste.',
 ['No bastidor, meu critério é simples: dá para entender o problema, a demonstração e o próximo passo? Nem todo erro precisa sumir. E nenhum efeito substitui uma mensagem clara. O processo serve para eu gravar com frequência sem transformar cada vídeo num projeto gigante.'], 'CONTEUDO',
 'CTA de conteúdo não leva mais a servidor. Só usar erro real disponível.'),
(30, 'Pergunta repetida e conhecimento', 'dono', 'RASTREAR', 'Consideração', 'CRESA',
 'Empilhar três perguntas iguais anonimizadas e transformar em resposta revisada.', 'Sua equipe já respondeu isso. Onde ficou?',
 'Se todo atendimento começa do zero, talvez a primeira automação seja organizar o que vocês já sabem.',
 ['Tem pergunta que a equipe responde várias vezes e cada pessoa explica de um jeito.',
  'O erro é ligar um agente a um conhecimento desatualizado e esperar consistência.',
  'Separe as dúvidas recorrentes, aprove as respostas e diga quando precisa chamar uma pessoa. Depois teste com exemplos reais anonimizados. A IA entra sobre uma base que alguém consegue revisar.'], 'FUNIL',
 'Inclui revisão e encaminhamento humano, não promessa de bot que resolve tudo.'),
(31, 'Consultoria antes de contratar', 'dono', 'MONETIZAR', 'Pré-conversão', 'AIDA',
 'Um PRD sem dados privados com prioridade, escopo e aceite destacados.', 'O que você leva antes da implementação?',
 'Você não precisa contratar um projeto inteiro para começar a organizar a decisão.',
 ['Na Sessão de Start, a gente olha o problema e documenta um PRD: prioridade, escopo, dependências e como avaliar a entrega.',
  'Isso ajuda a conversar com sua equipe ou seguir para um Sprint ou Implementação. São etapas diferentes. O valor pago na consultoria entra como crédito no projeto, conforme a condição da oferta.'], 'LASER',
 'Sai post genérico de preço por hora; entra objeção concreta à oferta vigente.'),
(32, 'Ferramentas pelo trabalho', 'dono', 'VIBE CODAR', 'Descoberta', 'COBA',
 'Três cartões de tarefas, sem logotipos: REGISTRAR / RESPONDER / MEDIR.', 'A lista de ferramentas começa antes dos nomes',
 'Quer uma lista de ferramentas? Eu começaria por uma lista do que a empresa precisa fazer.',
 ['Registrar a oportunidade, responder com contexto e medir o próximo passo. Agora veja quais ferramentas atuais já cobrem essas tarefas e onde existe uma lacuna.',
  'Essa comparação evita montar uma coleção de aplicativos sem um fluxo entre eles. Depois faz sentido escolher nomes, testar compatibilidade e calcular custo. A ferramenta tem trabalho a cumprir.'], 'INFRA',
 'Não promete lista pessoal/gratuita/sem afiliados que não foi verificada.'),
(33, 'Promessa da isca', 'dono', 'MONETIZAR', 'Consideração', 'CRESA',
 'Cartão “vou te dar um checklist” abrindo uma página de venda; fechar e mostrar o checklist.', 'O clique pode estar cobrando a promessa',
 'Você promete um material no vídeo e manda uma página de venda na mensagem?',
 ['A pessoa comentou para receber uma coisa. Se encontra outra, precisa decidir de novo se confia naquele caminho.',
  'O erro não é ter uma oferta. É trocar a recompensa pela oferta.',
  'Entregue o material anunciado, ajude a pessoa a usar e só depois apresente um próximo passo coerente. Isso é uma hipótese de melhoria para testar, não uma explicação automática para toda baixa conversão.'], 'FUNIL',
 'Corrige o principal gap do lote original; sem inventar vendas atribuídas por post.'),
(34, 'Diário do ciclo de conteúdo', 'ponte', 'MONETIZAR', 'Consideração', 'COBA',
 'Painel com colunas PUBLICADO / ENTREGUE / CLICADO; ocultar dados pessoais.', 'O número que eu não vou comemorar sozinho',
 'Minha meta é publicar pelo menos quatro Reels por dia. Mas eu não vou avaliar o ciclo só pelo volume.',
 ['Vou separar o que foi publicado de verdade, quais recompensas foram entregues e quais próximos passos tiveram sinal. Roteiro pronto não conta como vídeo no ar.',
  'Depois eu comparo temas e caminhos com as limitações dos dados. Se uma campanha não estiver rastreada, ela aparece como lacuna, não como zero vendas. Quero frequência que também produza aprendizado.'], 'CONTEUDO',
 'Prospectivo: não afirma que já publicou 35 nem que crença causou resultado.'),
(35, 'Convite sem diagnóstico gratuito implícito', 'dono', 'MONETIZAR', 'Pré-conversão', 'AAA',
 'Escolher um único cartão entre vários problemas e colocar “PRÓXIMA DECISÃO”.', 'Qual decisão está parada na sua empresa?',
 'Se você tem várias ideias de IA e não sabe qual vale executar primeiro, a próxima etapa pode ser uma conversa de escopo.',
 ['Na Sessão de Start, eu te ajudo a organizar o problema e sair com o PRD do projeto. É uma oferta paga, com condições e horários na página. Não inclui implementar tudo, nem promete venda garantida. O objetivo é decidir com mais clareza antes de construir.'], 'LASER',
 'Convite explícito, sem ameaçar prazo ou prometer contato gratuito que vira checkout.'),
]
